"""add constraints

Revision ID: 1fe5c694ace3
Revises: 5df89084091d
Create Date: 2026-05-05 21:37:38.501194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe5c694ace3'
down_revision: Union[str, Sequence[str], None] = '5df89084091d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_events', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'match_events', 'teams', ['team_id'], ['id'])
    op.drop_constraint(op.f('tournament_roles_tournament_id_fkey'), 'tournament_roles', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_roles', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_roles', type_='foreignkey')
    op.create_foreign_key(op.f('tournament_roles_tournament_id_fkey'), 'tournament_roles', 'tournaments', ['tournament_id'], ['id'])
    op.drop_constraint(None, 'match_events', type_='foreignkey')
    op.drop_column('match_events', 'team_id')
    # ### end Alembic commands ###
