"""cascade constraint on match event

Revision ID: 377e7779df1f
Revises: 5a0bdac0391c
Create Date: 2026-05-06 19:32:13.475275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377e7779df1f'
down_revision: Union[str, Sequence[str], None] = '5a0bdac0391c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('match_events_match_id_fkey'), 'match_events', type_='foreignkey')
    op.drop_constraint(op.f('match_events_team_id_fkey'), 'match_events', type_='foreignkey')
    op.create_foreign_key(None, 'match_events', 'matches', ['match_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'match_events', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_events', type_='foreignkey')
    op.drop_constraint(None, 'match_events', type_='foreignkey')
    op.create_foreign_key(op.f('match_events_team_id_fkey'), 'match_events', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('match_events_match_id_fkey'), 'match_events', 'matches', ['match_id'], ['id'])
    # ### end Alembic commands ###
