"""cascade constraint on match phases

Revision ID: 5a0bdac0391c
Revises: 60404620a27a
Create Date: 2026-05-06 19:20:06.194011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0bdac0391c'
down_revision: Union[str, Sequence[str], None] = '60404620a27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('match_phases_match_id_fkey'), 'match_phases', type_='foreignkey')
    op.create_foreign_key(None, 'match_phases', 'matches', ['match_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_phases', type_='foreignkey')
    op.create_foreign_key(op.f('match_phases_match_id_fkey'), 'match_phases', 'matches', ['match_id'], ['id'])
    # ### end Alembic commands ###
