"""add sport config

Revision ID: 5df89084091d
Revises: bc30b6255ec5
Create Date: 2026-05-04 21:15:56.093205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df89084091d'
down_revision: Union[str, Sequence[str], None] = 'bc30b6255ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_events', sa.Column('phase_id', sa.Integer(), nullable=True))
    op.add_column('sports', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sports', 'config')
    op.drop_column('match_events', 'phase_id')
    # ### end Alembic commands ###
